"""add_symbol_and_call_graph_tables

Revision ID: 1268d9d76ea7
Revises: 830a9166a089
Create Date: 2026-03-21 15:03:37.238778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1268d9d76ea7'
down_revision: Union[str, Sequence[str], None] = '830a9166a089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_functions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connected_repo_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('qualified_name', sa.String(length=1024), nullable=True),
    sa.Column('symbol_type', sa.String(length=32), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('return_type', sa.String(length=512), nullable=True),
    sa.Column('docstring', sa.Text(), nullable=True),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('class_name', sa.String(length=512), nullable=True),
    sa.Column('is_async', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connected_repo_id'], ['connected_repository.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['repository_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_functions_connected_repo_id'), 'repository_functions', ['connected_repo_id'], unique=False)
    op.create_index(op.f('ix_repository_functions_file_id'), 'repository_functions', ['file_id'], unique=False)
    op.create_index(op.f('ix_repository_functions_name'), 'repository_functions', ['name'], unique=False)
    op.create_table('function_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connected_repo_id', sa.Uuid(), nullable=False),
    sa.Column('source_function_id', sa.Uuid(), nullable=False),
    sa.Column('target_function_id', sa.Uuid(), nullable=False),
    sa.Column('call_line', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connected_repo_id'], ['connected_repository.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_function_id'], ['repository_functions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_function_id'], ['repository_functions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_function_calls_connected_repo_id'), 'function_calls', ['connected_repo_id'], unique=False)
    op.create_index(op.f('ix_function_calls_source_function_id'), 'function_calls', ['source_function_id'], unique=False)
    op.create_index(op.f('ix_function_calls_target_function_id'), 'function_calls', ['target_function_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_function_calls_target_function_id'), table_name='function_calls')
    op.drop_index(op.f('ix_function_calls_source_function_id'), table_name='function_calls')
    op.drop_index(op.f('ix_function_calls_connected_repo_id'), table_name='function_calls')
    op.drop_table('function_calls')
    op.drop_index(op.f('ix_repository_functions_name'), table_name='repository_functions')
    op.drop_index(op.f('ix_repository_functions_file_id'), table_name='repository_functions')
    op.drop_index(op.f('ix_repository_functions_connected_repo_id'), table_name='repository_functions')
    op.drop_table('repository_functions')
    # ### end Alembic commands ###
