"""add_github_oauth_and_connected_repository

Revision ID: 6b8f89dd47bc
Revises: 
Create Date: 2026-03-11 13:48:55.382070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b8f89dd47bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('connected_repository',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('repo_id', sa.String(length=128), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('clone_url', sa.String(length=1024), nullable=True),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connected_repository_id'), 'connected_repository', ['id'], unique=False)
    op.create_index(op.f('ix_connected_repository_user_id'), 'connected_repository', ['user_id'], unique=False)
    op.create_table('github_oauth_token',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('access_token', sa.String(length=1024), nullable=False),
    sa.Column('token_type', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=512), nullable=True),
    sa.Column('github_user_id', sa.String(length=128), nullable=True),
    sa.Column('github_username', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_oauth_token_github_user_id'), 'github_oauth_token', ['github_user_id'], unique=False)
    op.create_index(op.f('ix_github_oauth_token_id'), 'github_oauth_token', ['id'], unique=False)
    op.create_index(op.f('ix_github_oauth_token_user_id'), 'github_oauth_token', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_oauth_token_user_id'), table_name='github_oauth_token')
    op.drop_index(op.f('ix_github_oauth_token_id'), table_name='github_oauth_token')
    op.drop_index(op.f('ix_github_oauth_token_github_user_id'), table_name='github_oauth_token')
    op.drop_table('github_oauth_token')
    op.drop_index(op.f('ix_connected_repository_user_id'), table_name='connected_repository')
    op.drop_index(op.f('ix_connected_repository_id'), table_name='connected_repository')
    op.drop_table('connected_repository')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
