"""add_qc_events_and_qc_defects_tables

Revision ID: 7c8d9e0f1a2b
Revises: 1a2b3c4d5e6f
Create Date: 2026-06-24 19:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8d9e0f1a2b'
down_revision: Union[str, Sequence[str], None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qc_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('factory_id', sa.Uuid(), nullable=False),
    sa.Column('device_metadata', sa.JSON(), nullable=False),
    sa.Column('qc_event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_factory_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('execution_context', sa.JSON(), nullable=False),
    sa.Column('processing_duration_ms', sa.Integer(), nullable=False),
    sa.Column('processing_status', sa.String(length=32), nullable=False),
    sa.Column('validation_triggered', sa.Boolean(), nullable=False),
    sa.Column('processing_results', sa.JSON(), nullable=True),
    sa.Column('has_errors', sa.Boolean(), nullable=False),
    sa.Column('validation_error_count', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_events_event_id'), 'qc_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_qc_events_factory_id'), 'qc_events', ['factory_id'], unique=False)
    op.create_index(op.f('ix_qc_events_id'), 'qc_events', ['id'], unique=False)
    
    op.create_table('qc_defects',
    sa.Column('defect_event_id', sa.Uuid(), nullable=False),
    sa.Column('parent_qc_event_id', sa.Uuid(), nullable=True),
    sa.Column('factory_id', sa.Uuid(), nullable=False),
    sa.Column('defect_payload', sa.JSON(), nullable=False),
    sa.Column('defect_coordinates', sa.JSON(), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_factory_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_duration_ms', sa.Integer(), nullable=False),
    sa.Column('processing_status', sa.String(length=32), nullable=False),
    sa.Column('validation_triggered', sa.Boolean(), nullable=False),
    sa.Column('processing_results', sa.JSON(), nullable=True),
    sa.Column('has_errors', sa.Boolean(), nullable=False),
    sa.Column('validation_error_count', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_defects_defect_event_id'), 'qc_defects', ['defect_event_id'], unique=True)
    op.create_index(op.f('ix_qc_defects_factory_id'), 'qc_defects', ['factory_id'], unique=False)
    op.create_index(op.f('ix_qc_defects_batch_id'), 'qc_defects', ['batch_id'], unique=False)
    op.create_index(op.f('ix_qc_defects_parent_qc_event_id'), 'qc_defects', ['parent_qc_event_id'], unique=False)
    op.create_index(op.f('ix_qc_defects_id'), 'qc_defects', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qc_defects_id'), table_name='qc_defects')
    op.drop_index(op.f('ix_qc_defects_parent_qc_event_id'), table_name='qc_defects')
    op.drop_index(op.f('ix_qc_defects_batch_id'), table_name='qc_defects')
    op.drop_index(op.f('ix_qc_defects_factory_id'), table_name='qc_defects')
    op.drop_index(op.f('ix_qc_defects_defect_event_id'), table_name='qc_defects')
    op.drop_table('qc_defects')
    op.drop_index(op.f('ix_qc_events_id'), table_name='qc_events')
    op.drop_index(op.f('ix_qc_events_factory_id'), table_name='qc_events')
    op.drop_index(op.f('ix_qc_events_event_id'), table_name='qc_events')
    op.drop_table('qc_events')
    # ### end Alembic commands ###
