"""add_file_dependencies

Revision ID: 830a9166a089
Revises: 8f9acacad7aa
Create Date: 2026-03-14 14:36:41.153217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '830a9166a089'
down_revision: Union[str, Sequence[str], None] = '8f9acacad7aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_dependencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connected_repo_id', sa.Uuid(), nullable=False),
    sa.Column('source_file_id', sa.Uuid(), nullable=False),
    sa.Column('target_file_id', sa.Uuid(), nullable=False),
    sa.Column('import_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connected_repo_id'], ['connected_repository.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['repository_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_file_id'], ['repository_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_dependencies_connected_repo_id'), 'file_dependencies', ['connected_repo_id'], unique=False)
    op.create_index(op.f('ix_file_dependencies_source_file_id'), 'file_dependencies', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_file_dependencies_target_file_id'), 'file_dependencies', ['target_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_dependencies_target_file_id'), table_name='file_dependencies')
    op.drop_index(op.f('ix_file_dependencies_source_file_id'), table_name='file_dependencies')
    op.drop_index(op.f('ix_file_dependencies_connected_repo_id'), table_name='file_dependencies')
    op.drop_table('file_dependencies')
    # ### end Alembic commands ###
