"""create_repository_files_table

Revision ID: 8f9acacad7aa
Revises: 6b8f89dd47bc
Create Date: 2026-03-13 14:46:45.783461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f9acacad7aa'
down_revision: Union[str, Sequence[str], None] = '6b8f89dd47bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connected_repo_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('extension', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('is_binary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connected_repo_id'], ['connected_repository.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_files_connected_repo_id'), 'repository_files', ['connected_repo_id'], unique=False)
    op.create_index(op.f('ix_repository_files_user_id'), 'repository_files', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repository_files_user_id'), table_name='repository_files')
    op.drop_index(op.f('ix_repository_files_connected_repo_id'), table_name='repository_files')
    op.drop_table('repository_files')
    # ### end Alembic commands ###
